service: t-minus-showtime

frameworkVersion: '3'

custom:
  tableName: 'Users'
  wsgi:
    app: t-minus-showtime.app

provider:
  name: aws
  runtime: python3.7
  region: eu-west-2
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:eu-west-2:616727868396:table/Users"

  environment:
    USERS: ${self:custom.tableName}

functions:
  t-minus-showtime:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

	
package:
  patterns:
    - '!.env'
    - '!ISSUES.txt'
    - '!env/**'
    - '!handler_venv/**'
    - '!rundb.bat'
    - '!.vscode/**'
    - '!DynamoDB/**'
    - '!node_modules/**'

useDotenv: true
