"""base 3 tables

Revision ID: 217a3b191d8c
Revises: 
Create Date: 2019-05-22 15:43:18.170857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217a3b191d8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('tracked_films',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('film_title', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('film_id')
    )
    op.create_index(op.f('ix_tracked_films_film_title'), 'tracked_films', ['film_title'], unique=False)
    op.create_table('tracked_series',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('series_title', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_index(op.f('ix_tracked_series_series_title'), 'tracked_series', ['series_title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_series_series_title'), table_name='tracked_series')
    op.drop_table('tracked_series')
    op.drop_index(op.f('ix_tracked_films_film_title'), table_name='tracked_films')
    op.drop_table('tracked_films')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
