"""empty message

Revision ID: bdadb19113e5
Revises: 217a3b191d8c
Create Date: 2019-08-07 16:46:33.694338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdadb19113e5'
down_revision = '217a3b191d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracked_films', type_='foreignkey')
    op.create_foreign_key(None, 'tracked_films', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'tracked_series', type_='foreignkey')
    op.create_foreign_key(None, 'tracked_series', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_column('user', 'id')
    op.drop_constraint(None, 'tracked_series', type_='foreignkey')
    op.create_foreign_key(None, 'tracked_series', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'tracked_films', type_='foreignkey')
    op.create_foreign_key(None, 'tracked_films', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
